### ISSUE TITLE
Published or Released event is not created after release creation

### ISSUE THREAD

**Issue by nitin-jci** [actions/create-release#105]
Hi Team,

I have two workflows in my project:
1. create-release workflow
2. release build

Release build is supposed to be triggered on  
```
on:
  release:
    types: [ published, released ]

```
When I create the release manually from the UI, release build gets triggered. However, with create-release workflow my later workflow does not get triggered.
Kindly let me know if you need any other information.

**Comment by rue-kcarlton** [comment]
It looks like the behavior is not the fault of this action... I did a test with using my GitHub personal access token instead of the default `secrets.GITHUB_TOKEN` and it triggers the `released` event as if I did the release creation via the UI.

**Comment by nitin-jci** [comment]
Thank you for the information. I tried with secret.PAT and it worked.
Can you guys please update the README.md. That suggests secrets.GITHUB_TOKEN to use.
`env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token`

Closing this issue.
