### ISSUE TITLE
documentation request: what are the minimum permissions necessary for GITHUB_TOKEN?

### ISSUE THREAD

**Issue by jasonkarns** [actions/create-release#15]
According to the example workflow, GITHUB_TOKEN is necessary. However, there isn't any mention of what permissions that token needs in order to complete the release creation.

**Comment by imjohnbo** [comment]
Hey @jasonkarns! `GITHUB_TOKEN` is a special, automatically-created token scoped to the repository whose workflow triggers the run. The documentation [here](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#github_token-secret) might be useful.

**Comment by IAmHughes** [comment]
Closing, thanks @imjohnbo for the quick response! @jasonkarns if you have more questions please feel free to re-open 😄

**Comment by jasonkarns** [comment]
👍 i might suggest adding a comment to that effect in the example workflow? (this is my second workflow; the first one needed a token to access a _different_ repo so I was expecting to need to create another PAT)

(also, FYI I can't re-open as non-collaborator. don't need to reopen, though. just mentioning)

**Comment by IAmHughes** [comment]
@jasonkarns I'll do that right now by adding a comment to the workflow example, thanks!
