### ISSUE TITLE
Make "release_name" optional

### ISSUE THREAD

**Issue by niknetniko** [actions/create-release#26]
I would like to use this action to create a release based on a tag, using the tag text as the release name and body (e.g. the first line of the tag text is the release name, the rest is the body).

On the web ui I can just leave the release name empty, and it will use the first line as title, prefixed with the tag.

Is there any reason the `release_name` parameter is required?

**Comment by 1138-4EB** [comment]
Ref #11

**Comment by mscoutermarsh** [comment]
Fixed here: https://github.com/actions/create-release/pull/75
