### ISSUE TITLE
Body value is not visible

### ISSUE THREAD

**Issue by nazarimilad** [actions/create-release#30]
So when I set a value for the body of the release, like here for example using 'Testing' as the body:

![image](https://user-images.githubusercontent.com/23218676/71492772-b5fd3400-2831-11ea-977d-a9fa9bfd7647.png)

The string ('Testing') simply does not show up:

![image](https://user-images.githubusercontent.com/23218676/71492786-cca38b00-2831-11ea-8cba-06b9b5eff40d.png)

**Comment by k-takata** [comment]
I faced the same problem.
The body value was added after v1.0.0, and not tagged yet.
So, you need to use `actions/create-release@master`.

**Comment by nazarimilad** [comment]
I see. Thank you!
