### ISSUE TITLE
The body content no show

### ISSUE THREAD

**Issue by GuanWeihua** [actions/create-release#35]
<img width="554" alt="批注 2020-01-10 163245" src="https://user-images.githubusercontent.com/3953552/72138016-dc40d900-33c6-11ea-9447-aa0451c4c5a7.png">
<img width="856" alt="批注 2020-01-10 163634" src="https://user-images.githubusercontent.com/3953552/72138251-6c7f1e00-33c7-11ea-88be-69c4c7ecea82.png">

**Comment by eine** [comment]
That feature was added to master after v1 was tagged: https://github.com/actions/create-release/commits/master. You need to use `master`, or wait until `v1.0.1` is tagged (and `v1` updated accordingly).

**Comment by GuanWeihua** [comment]
> cc

think you

**Comment by GuanWeihua** [comment]
> That feature was added to master after v1 was tagged: https://github.com/actions/create-release/commits/master. You need to use `master`, or wait until `v1.0.1` is tagged (and `v1` updated accordingly).
> 
> **EDIT**
> 
> Actually, it seems that v1 does not currently point to `v1.0.0` (which it should). It is pointing to a commit without full semver tag.
> 
> /cc @ethomson

thank you.
