### ISSUE TITLE
Input required and not supplied: GITHUB_TOKEN

### ISSUE THREAD

**Issue by funnyPan** [actions/create-release#36]
[error]Input required and not supplied: GITHUB_TOKEN
[error]Node run failed with exit code 1

**Comment by imjohnbo** [comment]
Hi @funnyPan, note the `README` [example](https://github.com/actions/create-release#example-workflow---create-a-release) and the line:

```yaml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
```

Please reopen the issue if you continue to have problems.
