### ISSUE TITLE
Release based on PR

### ISSUE THREAD

**Issue by tenhobi** [actions/create-release#5]
Hello, is there any functionality based on, for example, PR label so I can release with major/minor/patch update to release's tag?

I need it to automate release deploying with version changes (https://github.com/tenhobi/bachelors-thesis/issues/8) 

e.g. :

- release v0.1.1
then PR w/ label "minor"
- release v0.2.0
then PR w/ label "major"
- release v1.0.0

**Comment by K-Phoen** [comment]
Shameless plug here: the behavior you're describing is implemented by this action → https://github.com/K-Phoen/semver-release-action
