### ISSUE TITLE
Releases created by this action ignores by  other  workflows

### ISSUE THREAD

**Issue by lechen26** [actions/create-release#52]
we have  2 workflows:
- workflow to automate the release creation using  this create-release action.
   the release indeed created using github-action bot.
- workflow  to automate the  deployment while triggered for every  new  Release that being created. (on: release types: [ created])

the thing when releases created  by users  everything works  as before and deployment triggered.
when the release created through this action, the deploy workflow does not runs , like the event o of release  is not  firing.
according to  this  thread https://github.community/t5/GitHub-Actions/Github-actions-workflow-not-triggering-with-tag-push/td-p/39685 its seems like  a  known issue, and using  our own SECRET it works as before.

anything we  can do?
it  requires a personal user token or  to  get  additional seat.

**Comment by romariolopezc** [comment]
I can confirm. This also happens to me

**Comment by niklasravnsborg** [comment]
I also have the same problem. In the documentation of this action it says this:

```
This will create a Release, as well as a release event, which could be handled by a third party service, or by GitHub Actions for additional uses, for example the @actions/upload-release-asset GitHub Action. This uses the GITHUB_TOKEN provided by the virtual environment, so no new token is needed.
```

**Comment by cainlevy** [comment]
Given the linked thread, it seems like this is a documentation issue. It would be helpful if this limitation was stated clearly and up front, along with the personal token workaround.
