### ISSUE TITLE
Release name is not required by underlying API

### ISSUE THREAD

**Issue by Bilge** [actions/create-release#74]
Despite the [underlying API](https://developer.github.com/v3/repos/releases/#create-a-release) not requiring a release name to be specified, [this module still requires it](https://github.com/actions/create-release/blob/master/src/create-release.js#L17). It seems to me this module should be a thin wrapper around the underlying API, which means it should not change the rules about what is required.

**Comment by eine** [comment]
@Bilge, you might consider writing your own thiner wrapper in Python (as a Docker Action). See, for example, [eine/tip](https://github.com/eine/tip). See also [PyGithub/PyGithub](https://github.com/PyGithub/PyGithub) and [pygithub.rtfd.io](https://pygithub.readthedocs.io/en/latest/examples.html).

**Comment by mscoutermarsh** [comment]
Merged in the PR
